package com.ripaex.arkxlmbridge;

public class Constants {

	public static final String TESTNET_ENDPOINT = "https://horizon-testnet.stellar.org";

	public static final String SECRET_1 = "SBWTWSZHEN6Q2RKMVMVGQIPLUA72TI3CJ6TJFEQIHX2WS3J5ZZAT24ZH";
	public static final String PUBLIC_1 = "GALTIA73LATASBGO63SG3EK7OFH5FT4P7ODI2HRNNFI4ZVWMMD5KQH2W";
	public static final String SECRET_2 = "SBRJ4XGOTJNWGYQR43H3GSIQMO6CDASBR6MU6CMNAZ53FKEMTMRTMZ5O";
	public static final String PUBLIC_2 = "GBSIQARNKWZE4N52VV5ESNVXBCTLJZJRWKVGDHOX3D7G3ZRB7LWEHIN3";
	public static final String SECRET_3 = "SCKWF64LGJIOZDG3D7KI3WAQWYKI2DR7NEIDTJN4QAFAVNIS4RORICN5";
	public static final String PUBLIC_3 = "GCIAWJCOYQEB64TC5JWB5YXCEPFPL6C4MEV425V5GPARPO2OMPGYDIIU";

}
